repo:
  - '*'

change-module-cart:
  - src/modules/cart/**/*

change-module-email:
  - src/modules/email/**/*

change-module-payment:
  - src/modules/payment/**/*

change-module-shipping:
  - src/modules/shipping/**/*

change-module-minicart-resume:
  - src/modules/minicart-resume/**/*

change-module-profile:
  - src/modules/profile/**/*

change-style-cart:
  - src/styles/cart/**/*

change-style-email:
  - src/styles/email/**/*

change-style-payment:
  - src/styles/payment/**/*

change-style-shipping:
  - src/styles/shipping/**/*

change-style-minicart-resume:
  - src/styles/minicart-resume/**/*

change-style-profile:
  - src/styles/profile/**/*
