label:
  - name: change-module-cart
    pattern: 'src/modules/cart/**/*'
    color: 'DB5461'
  - name: change-module-email
    pattern: 'src/modules/email/**/*'
    color: 'FF8C42'
  - name: change-module-minicart-resume
    pattern: 'src/modules/minicart-resume/**/*'
    color: 'FFC107'
  - name: change-module-payment
    pattern: 'src/modules/payment/**/*'
    color: '00BEBE'
  - name: change-module-profile
    pattern: 'src/modules/profile/**/*'
    color: '7C83FD'
  - name: change-module-shipping
    pattern: 'src/modules/shipping/**/*'
    color: '9C52AB'
  - name: change-style-cart
    pattern: 'src/styles/cart/**/*'
    color: 'FF6B6B'
  - name: change-style-email
    pattern: 'src/styles/email/**/*'
    color: 'F5A962'
  - name: change-style-minicart-resume
    pattern: 'src/styles/minicart-resume/**/*'
    color: 'F4D35E'
  - name: change-style-payment
    pattern: 'src/styles/payment/**/*'
    color: '41EAD4'
  - name: change-style-profile
    pattern: 'src/styles/profile/**/*'
    color: 'A0A8D9'
  - name: change-style-shipping
    pattern: 'src/styles/shipping/**/*'
    color: '8B5B9B'
