repo 📁:
  - '*'

module:cart 🛒:
  - 'src/modules/cart/**/*'

module:email 📧:
  - 'src/modules/email/**/*'

module:payment 💳:
  - 'src/modules/payment/**/*'

module:shipping 🚚:
  - 'src/modules/shipping/**/*'
module:minicart:resume 🛒:
  - 'src/modules/minicart-resume/**/*'

module:profile 👤:
  - 'src/modules/profile/**/*'

style:cart 🛒:
  - 'src/styles/cart/**/*'

style:email 📧:
  - 'src/styles/email/**/*'

style:payment 💳:
  - 'src/styles/payment/**/*'

style:shipping 🚚:
  - 'src/styles/shipping/**/*'

style:minicart:resume 🛒:
  - 'src/styles/minicart-resume/**/*'

style:profile 👤:
  - 'src/styles/profile/**/*'

dependencies 📦:
  - 'package.json'

workflows 📝:
  - '.github/workflows/**/*'
